//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnagramSolver.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnagramSolver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a
        ///a&apos;
        ///a-
        ///A&amp;M
        ///A&amp;P
        ///A.
        ///A.A.A.
        ///A.B.
        ///A.B.A.
        ///A.C.
        ///A.D.
        ///A.D.C.
        ///A.F.
        ///A.F.A.M.
        ///A.G.
        ///A.H.
        ///A.I.
        ///A.I.A.
        ///A.I.D.
        ///A.L.
        ///A.L.P.
        ///A.M.
        ///A.M.A.
        ///A.M.D.G.
        ///A.N.
        ///a.p.
        ///a.r.
        ///A.R.C.S.
        ///A.U.
        ///A.U.C.
        ///A.V.
        ///a.w.
        ///A.W.O.L.
        ///A/C
        ///A/F
        ///A/O
        ///A/P
        ///A/V
        ///A1
        ///A-1
        ///A4
        ///A5
        ///AA
        ///AAA
        ///AAAA
        ///AAAAAA
        ///AAAL
        ///AAAS
        ///Aaberg
        ///Aachen
        ///AAE
        ///AAEE
        ///AAF
        ///AAG
        ///aah
        ///aahed
        ///aahing
        ///aahs
        ///AAII
        ///aal
        ///Aalborg
        ///Aalesund
        ///aalii
        ///aaliis
        ///aals
        ///Aalst
        ///Aalto
        ///AAM
        ///AAMSI
        ///Aandahl
        ///A-and-R
        ///Aani
        ///AAO
        ///AAP
        ///AAPSS
        ///Aaqbiye
        ///Aar
        ///Aara
        ///Aarau
        ///AARC
        ///aardvark
        ///aardvarks
        ///aardwolf
        ///aardwolves
        ///Aaren
        ///Aargau
        ///aargh
        ///Aarhus
        ///Aarika
        ///Aaron
        ///Aaro [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string en_US {
            get {
                return ResourceManager.GetString("en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABS
        ///ADN
        ///ADSL
        ///Abad
        ///AbadÃ­a
        ///Abajo
        ///AbalÃ¡
        ///Abancay
        ///Abanga
        ///AbapÃ³
        ///Abasolo
        ///Abasticos
        ///Abdullah
        ///Abedules
        ///Abejas
        ///Abejones
        ///Abejorral
        ///Abel
        ///Abelardo
        ///Abello
        ///Aberastain
        ///Abicin
        ///Aboabo
        ///Abona
        ///AbongÃ¡n
        ///AborlÃ¡n
        ///Abra
        ///Abraham
        ///Abre
        ///Abreus
        ///AbriaquÃ­
        ///Abucay
        ///Abulug
        ///Acacias
        ///Acacoyagua
        ///AcacÃ­as
        ///Academia
        ///Acajete
        ///Acala
        ///Acalayong
        ///Acambay
        ///Acanceh
        ///AcandÃ­
        ///Acapetahua
        ///Acaponeta
        ///Acapulco
        ///Acaricuara
        ///Acarigua
        ///AcarÃ­
        ///Acas
        ///Acateno
        ///Acatepec
        ///Acatic
        ///AcatlÃ¡n
        ///Acatzingo
        ///AcaxochitlÃ¡n
        ///Acaya
        ///Acayucan
        ///Accha
        ///Accomarca
        ///Acequia
        ///Acevedo
        ///Acha
        ///Achacachi
        ///Acha [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string es_MX {
            get {
                return ResourceManager.GetString("es_MX", resourceCulture);
            }
        }
    }
}
